### ISSUE TITLE
Deadlock happening in *broadcast

### ISSUE THREAD

**Issue by party79** [googollee/go-socket.io#152]
I have successfully managed to get it to deadlock where I have a page that is connected on a mac using safari and I send the mac to sleep, causing (_broadcast).Send to lock up in io wait and then opening another page on another system which runs (_broadcast).Join and it deadlocks the whole process

I don't know if it is the mac+safari+sleep that is causing the io wait, but Send locking up in io wait is not good, it may come good in time and unlock, but I have had a process in io wait from Send for 10 minutes, and that is too long

**Comment by party79** [comment]
Send in IO wait
```
goroutine 114 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fdadf1a07a0, 0x77, 0x32)
	/opt/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4202be140, 0x77, 0xc421d232f8, 0xc4200840a0)
	/opt/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitWrite(0xc4202be140, 0xbe50a0, 0xc4200840a0)
	/opt/go/src/net/fd_poll_runtime.go:82 +0x34
net.(*netFD).Write(0xc4202be0e0, 0xc42066f20a, 0xe9a, 0x2804, 0x216, 0xbe50a0, 0xc4200840a0)
	/opt/go/src/net/fd_unix.go:329 +0x347
net.(*conn).Write(0xc420234b88, 0xc42066f20a, 0xe9a, 0x2804, 0x0, 0x0, 0x0)
	/opt/go/src/net/net.go:185 +0x70
github.com/gorilla/websocket.(*Conn).write(0xc4205b2b40, 0x1, 0x0, 0x0, 0x0, 0xc421d23498, 0x2, 0x2, 0x0, 0x0)
	/xxxx/xxxxxxx/src/github.com/gorilla/websocket/conn.go:339 +0x149
github.com/gorilla/websocket.(*Conn).flushFrame(0xc4205b2b40, 0x493801, 0x0, 0x0, 0x0, 0xc421d23558, 0x4bbde0)
	/xxxx/xxxxxxx/src/github.com/gorilla/websocket/conn.go:523 +0x2e4
github.com/gorilla/websocket.(*messageWriter).Close(0xc42023bd58, 0xc421d23548, 0xc421d23558)
	/xxxx/xxxxxxx/src/github.com/gorilla/websocket/conn.go:642 +0x71
github.com/googollee/go-engine.io/parser.(*PacketEncoder).Close(0xc420d055a0, 0x9e4f18, 0xc420d055c0)
	/xxxx/xxxxxxx/src/github.com/googollee/go-engine.io/parser/packet.go:114 +0x38
github.com/googollee/go-engine%2eio.(*connWriter).Close(0xc420d055c0, 0x0, 0x0)
	/xxxx/xxxxxxx/src/github.com/googollee/go-engine.io/ioutil.go:49 +0x6f
github.com/googollee/go-socket%2eio.(*encoder).encodePacket(0xc421d23778, 0x2, 0x0, 0x0, 0xffffffffffffffff, 0x8c8420, 0xc420d05580, 0x0, 0x0, 0x0)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/parser.go:128 +0x52c
github.com/googollee/go-socket%2eio.(*encoder).Encode(0xc421d23778, 0x2, 0x0, 0x0, 0xffffffffffffffff, 0x8c8420, 0xc420d05580, 0x0, 0xc420d05570, 0xc42061ee00)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/parser.go:82 +0xb2
github.com/googollee/go-socket%2eio.(*socket).send(0xc421724140, 0xc420d05560, 0x2, 0x2, 0xc42061ee00, 0x1)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/socket.go:80 +0x1ae
github.com/googollee/go-socket%2eio.(*socketHandler).Emit(0xc421567c50, 0xc4206951d8, 0x6, 0xc42061ee00, 0x1, 0x1, 0xc420818110, 0xc05fb0)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/handler.go:81 +0x315
github.com/googollee/go-socket%2eio.(*socket).Emit(0xc421724140, 0xc4206951d8, 0x6, 0xc42061ee00, 0x1, 0x1, 0x0, 0x0)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/socket.go:63 +0x64
github.com/googollee/go-socket%2eio.(*broadcast).Send(0xc4202b8320, 0x0, 0x0, 0xc42061ee40, 0x7, 0xc4206951d8, 0x6, 0xc42061ee00, 0x1, 0x1, ...)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/adapter.go:66 +0x15c
github.com/googollee/go-socket%2eio.(*baseHandler).BroadcastTo(0xc4202b6330, 0x98e588, 0x6, 0xc4206951d8, 0x6, 0xc42061ee00, 0x1, 0x1, 0xc421d23ad8, 0x44edbe)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/handler.go:120 +0xc4
github.com/googollee/go-socket%2eio.(*Server).BroadcastTo(0xc4202b8340, 0x98e588, 0x6, 0xc4206951d8, 0x6, 0xc42061ee00, 0x1, 0x1)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/server.go:92 +0x83

*** My Code ***
```

Join in semacquire
```
goroutine 5519293 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc4202b832c)
	/opt/go/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc4202b8328)
	/opt/go/src/sync/mutex.go:85 +0xd0
sync.(*RWMutex).Lock(0xc4202b8328)
	/opt/go/src/sync/rwmutex.go:86 +0x31
github.com/googollee/go-socket%2eio.(*broadcast).Join(0xc4202b8320, 0xc421b7b760, 0x11, 0xbeb400, 0xc420f1ce00, 0x10, 0x10)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/adapter.go:32 +0x40
github.com/googollee/go-socket%2eio.(*socketHandler).Join(0xc4212b1260, 0xc4204e7ad0, 0x10, 0x0, 0x0)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/handler.go:95 +0x89

*** My Code ***

reflect.Value.call(0x8f8720, 0xc42039c3a0, 0x13, 0x98cd10, 0x4, 0xc420278be0, 0x3, 0x3, 0x16, 0x8b98e0, ...)
	/opt/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x8f8720, 0xc42039c3a0, 0x13, 0xc420278be0, 0x3, 0x3, 0x8b3a01, 0xc4207c7c38, 0x7ba982)
	/opt/go/src/reflect/value.go:302 +0xa4
github.com/googollee/go-socket%2eio.(*caller).Call(0xc420f1d280, 0xbeb400, 0xc420f1ce00, 0xc421451c50, 0x3, 0x3, 0xc4214f3001, 0x0, 0x0)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/caller.go:81 +0x2d7
github.com/googollee/go-socket%2eio.(*socketHandler).onPacket(0xc4212b1260, 0xc4207c7f20, 0xc4207c7eb0, 0x0, 0xc42032e270, 0x0, 0x0, 0x0)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/handler.go:170 +0x1d0
github.com/googollee/go-socket%2eio.(*socket).loop(0xc420f1ce00, 0x0, 0x0)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/socket.go:140 +0x305
github.com/googollee/go-socket%2eio.(*Server).loop.func1(0xc420f1ce00)
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/server.go:103 +0x2b
created by github.com/googollee/go-socket%2eio.(*Server).loop
	/xxxx/xxxxxxx/src/github.com/googollee/go-socket.io/server.go:104 +0xa9
```

**Comment by party79** [comment]
you should maybe use ```github.com/gorilla/websocket.(*Conn).SetWriteDeadline``` and the writes would time out (probably a go-engine.io thing)
also maybe not have ```github.com/googollee/go-socket%2eio.(*broadcast).Send``` wait for ```github.com/googollee/go-socket%2eio.(*socketHandler).Emit```, maybe fire it in it's own goroutine

**Comment by party79** [comment]
Added pull requests re this, take or leave and do your own thing

**Comment by googollee** [comment]
I have done it in go-engine.io branch v1.4. You can check the code.

Since v1.4 break the compatible, I'm working on new version of go-socket.io now which use v1.4 as transport layer. Please wait it finish.

**Comment by party79** [comment]
I can wait, my program crashes on the deadlock and restarts, so it is only a minor inconvenience.

**Comment by googollee** [comment]
API will change. You can find codes on v1.4 branch, which is kind of working, but not stable and lack of testing.

**Comment by jjhesk** [comment]
@googollee why the boardcast function is gone in 1.4 now?

**Comment by erkie** [comment]
Closed because of old version of go-socket.io
