### ISSUE TITLE
[QUESTION] Time-consuming task in `OnEvent` will panic `concurrent write to websocket connection`

### ISSUE THREAD

**Issue by StartAt24** [googollee/go-socket.io#260]
When i do something which takes a long time in. `OnEvent`.
It will case a `panic: concurrent write to websocket connection`

Here is my server code:
```Go
	server.OnEvent("/", "test", func(s socketio.Conn) string{
		log.Error("Got ssss test")
		time.Sleep(time.Second* 40)
		log.Error("sleep done")	
		return "hello"
	})
```
If not `return anything`. It's fine.

Here is my client code:
```javascript
 var socket = io.connect('http://' + document.domain + ':' + location.port, {timeout: 60000, transports: ['websocket']})

        function test_xxx(){
            socket.emit("test", function(data){
                console.log(data)
            })
        }
```
Here is the error:
```
panic: concurrent write to websocket connection

goroutine 62 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0004b1710, 0xc0001f6201, 0x0, 0x0, 0x0, 0x7f4b910f66d0, 0x0)
        /home/daijunjie/lab/Go/src/github.com/gorilla/websocket/conn.go:597 +0x62f
github.com/gorilla/websocket.(*messageWriter).Close(0xc0004b1710, 0x2000, 0xc000689be0)
        /home/daijunjie/lab/Go/src/github.com/gorilla/websocket/conn.go:711 +0x62
github.com/gorilla/websocket.(*Conn).beginMessage(0xc000568420, 0xc0001f62d0, 0x1, 0xc00043e370, 0xc0003e7e60)
        /home/daijunjie/lab/Go/src/github.com/gorilla/websocket/conn.go:460 +0x244
github.com/gorilla/websocket.(*Conn).NextWriter(0xc000568420, 0x1, 0xf4a140, 0xc000384501, 0xc0001949c0, 0x60)
        /home/daijunjie/lab/Go/src/github.com/gorilla/websocket/conn.go:500 +0x53
github.com/googollee/go-engine.io/transport/websocket.wrapper.NextWriter(0xc000568420, 0xc0000cdc00, 0xc000094700, 0x7f4b910f6008, 0x0, 0xc000434bc0)
        /home/daijunjie/lab/Go/src/github.com/googollee/go-engine.io/transport/websocket/wrapper.go:47 +0x42
github.com/googollee/go-engine.io/packet.(*encoder).NextWriter(0xc0004da370, 0xc0001ba000, 0x4, 0x4481fb, 0xf4a140, 0xc0001ba0c0, 0xc00040cfb0)
        /home/daijunjie/lab/Go/src/github.com/googollee/go-engine.io/packet/encoder.go:20 +0x40
github.com/googollee/go-engine%2eio.(*session).nextWriter(0xc0004cc2c0, 0x0, 0x4, 0x0, 0x1, 0xc00011fe00, 0x1)
        /home/daijunjie/lab/Go/src/github.com/googollee/go-engine.io/session.go:155 +0x69
github.com/googollee/go-engine%2eio.(*session).NextWriter(0xc0004cc2c0, 0x0, 0xc0003eac20, 0x0, 0xc0001ba0a8, 0xc000689ef4)
        /home/daijunjie/lab/Go/src/github.com/googollee/go-engine.io/session.go:103 +0x3d
github.com/googollee/go-socket.io/parser.(*Encoder).Encode(0xc0004da450, 0x3, 0x0, 0x0, 0x0, 0x1, 0xc0004da4f0, 0x1, 0x1, 0xc0004117d0, ...)
        /home/daijunjie/lab/Go/src/github.com/googollee/go-socket.io/parser/encoder.go:29 +0x4d
github.com/googollee/go-socket%2eio.(*conn).serveWrite(0xc000414150)
        /home/daijunjie/lab/Go/src/github.com/googollee/go-socket.io/conn.go:183 +0x1be
created by github.com/googollee/go-socket%2eio.(*conn).connect
        /home/daijunjie/lab/Go/src/github.com/googollee/go-socket.io/conn.go:113 +0x22a
```

It seems that it takes too long, so the client has disconnected. I have tried to set `timeout:50000` in client, but it doesn't work. 
Is there any setting in server to solve this problem?

**Comment by StartAt24** [comment]
I have find this setting, and it seems solved my problem.
Here is my code:
```Go
opt := engineio.Options{ PingTimeout: time.Minute*2, PingInterval: time.Minute}
server, err:= socketio.NewServer(&opt)
```
It wonn't case `panic`. But still got `socketio closed`. 
I donn't know if it is the right way to do it.

**Comment by camstuart** [comment]
Interesting problem.

Generally, inside these types of handlers, I place any implementation code into a goroutine.
The main reason is that you don't want the handler to block. Otherwise, other events may not get handled, especially if you expect the workload for receiving a message to take some time, so something like this:

```go
server.OnEvent("/", "test", func(s socketio.Conn) string {
		log.Print("Got ssss test")

		go func() {
			log.Println("I am working in a separate go routine (thread), so you don't get blocked!")
			time.Sleep(time.Second * 40)
			log.Println("sleep done")
		}()

		return "hello"
	})
```
