### ISSUE TITLE
[BUG]panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by cheaterlin** [googollee/go-socket.io#287]
**Describe the bug**
as the title said, it panic usually

**To Reproduce**
I started the server as the following code. As a message pushing server, i have saved the 'socketio.Conn' after  server.OnConnect is called, and use a sync.Mutex to protect it from concurrent write. When OnDisconnect or server.OnError is called, i will lock and use a bool value named closed to protect the 'socketio.Conn' from far more writting. but, it still panic, sad.
It should be noted that the client connected me use Websocket only, someday I will use long polliing too.
```
// start socketio server
func (s *Server) socketioServe() error {
	server, err := socketio.NewServer(nil)
	if err != nil {
		return err
	}

	// ---- register socketio
	server.OnConnect("/", s.app.Connect)
	server.OnEvent("/", "login", s.app.Login)
	server.OnDisconnect("/", s.app.Disconnect)
	server.OnError("/", s.app.DisconnectOnError)

	go func() {
		_ = server.Serve()
	}()
	defer func() {
		_ = server.Close()
	}()

	http.Handle("/tim/socket.io/", server)
	http.Handle("/", http.FileServer(http.Dir("./asset")))

	port := *s.app.ConfigStore.Get().ServiceSettings.WebPort
	addr := ":" + port
	return http.ListenAndServe(addr, nil)
}
```

**Expected behavior**
robust protect on the Websocket conn write/close, make it don't panic

**Environment (please complete the following information):**
 - Go version: v1.13.4
 - Server version : master version now(Commits on Nov 9, 2019)
 - Client version: 2.1.1 js

**Additional context**
panic info 1, this appear more than once ->
```
panic: concurrent write to websocket connection

goroutine 86921 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc00074a4b0, 0xc000426101, 0x0, 0x0, 0x0, 0xc0001edb20, 0x42ee91)
	/data/cheaterlin/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:610 +0x612
github.com/gorilla/websocket.(*messageWriter).Close(0xc00074a4b0, 0xaec73c, 0xc0001edb50)
	/data/cheaterlin/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:724 +0x62
github.com/googollee/go-engine%2eio.(*writer).Close.func1()
	/data/cheaterlin/go/pkg/mod/github.com/googollee/go-engine.io@v1.4.2/util.go:26 +0x8a
sync.(*Once).doSlow(0xc00074a4f8, 0xc0001edc18)
	/data/cheaterlin/go_versions/1.13.4/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/data/cheaterlin/go_versions/1.13.4/go/src/sync/once.go:57
github.com/googollee/go-engine%2eio.(*writer).Close(0xc00074a4e0, 0x0, 0x0)
	/data/cheaterlin/go/pkg/mod/github.com/googollee/go-engine.io@v1.4.2/util.go:23 +0x7d
github.com/googollee/go-socket.io/parser.(*Encoder).writePacket(0xc00048f3f0, 0xe4a340, 0xc00074a4e0, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc0002c00a0, 0x2, ...)
	/data/cheaterlin/go/pkg/mod/github.com/googollee/go-socket.io@v1.4.3-0.20191109153049-7451e2f8c2e0/parser/encoder.go:119 +0x367
github.com/googollee/go-socket.io/parser.(*Encoder).Encode(0xc00048f3f0, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc0002c00a0, 0x2, 0x2, 0x0, ...)
	/data/cheaterlin/go/pkg/mod/github.com/googollee/go-socket.io@v1.4.3-0.20191109153049-7451e2f8c2e0/parser/encoder.go:35 +0xd3
github.com/googollee/go-socket%2eio.(*conn).serveWrite(0xc00023a000)
	/data/cheaterlin/go/pkg/mod/github.com/googollee/go-socket.io@v1.4.3-0.20191109153049-7451e2f8c2e0/conn.go:183 +0x1da
created by github.com/googollee/go-socket%2eio.(*conn).connect
	/data/cheaterlin/go/pkg/mod/github.com/googollee/go-socket.io@v1.4.3-0.20191109153049-7451e2f8c2e0/conn.go:113 +0x229
```

panic info 2 ->
```
panic: concurrent write to websocket connection

goroutine 104621 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0005aa900, 0xc0003bfb01, 0x0, 0x0, 0x0, 0xc000420060, 0xc0003bfbd8)
	/data/landun/workspace/go_application/vendor/github.com/gorilla/websocket/conn.go:610 +0x62f
github.com/gorilla/websocket.(*messageWriter).Close(0xc0005aa900, 0xd39280, 0xc000420060)
	/data/landun/workspace/go_application/vendor/github.com/gorilla/websocket/conn.go:724 +0x62
github.com/googollee/go-engine%2eio.(*writer).Close.func1()
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-engine.io/util.go:26 +0x80
sync.(*Once).Do(0xc0005aa948, 0xc0003bfc48)
	/data/bkdevops/apps/golang/1.12.4/src/sync/once.go:44 +0xb3
github.com/googollee/go-engine%2eio.(*writer).Close(0xc0005aa930, 0x0, 0x0)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-engine.io/util.go:23 +0x6c
github.com/googollee/go-engine%2eio.(*session).NextReader.func1(0xc000420000, 0xc0003bfd00, 0xe2d5a0, 0xc0005aa8d0, 0xc0005aa8d0, 0x0)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-engine.io/session.go:83 +0x12e
github.com/googollee/go-engine%2eio.(*session).NextReader(0xc000420000, 0xc0005be2d0, 0x1, 0x1, 0x3, 0x0)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-engine.io/session.go:84 +0xc0
github.com/googollee/go-socket.io/parser.(*Decoder).DecodeHeader(0xc0006f8280, 0xc000797f78, 0xc0003a7a90, 0x0, 0x18a8)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-socket.io/parser/decoder.go:58 +0x48
github.com/googollee/go-socket%2eio.(*conn).serveRead(0xc0002420e0)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-socket.io/conn.go:195 +0xcc
created by github.com/googollee/go-socket%2eio.(*conn).connect
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-socket.io/conn.go:114 +0x24f
```

panic info 3 ->
```
panic: concurrent write to websocket connection

goroutine 140767 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0002cf890, 0xc000317401, 0x0, 0x0, 0x0, 0x7fb260368460, 0x0)
	/data/landun/workspace/go_application/vendor/github.com/gorilla/websocket/conn.go:610 +0x62f
github.com/gorilla/websocket.(*messageWriter).Close(0xc0002cf890, 0x3, 0xc00057fbe0)
	/data/landun/workspace/go_application/vendor/github.com/gorilla/websocket/conn.go:724 +0x62
github.com/gorilla/websocket.(*Conn).beginMessage(0xc000608420, 0xc0003174a0, 0x1, 0xd39280, 0xc00057fc58)
	/data/landun/workspace/go_application/vendor/github.com/gorilla/websocket/conn.go:473 +0x244
github.com/gorilla/websocket.(*Conn).NextWriter(0xc000608420, 0x1, 0xc000741e40, 0xc00057fc68, 0xc00057fc88, 0x462aa2)
	/data/landun/workspace/go_application/vendor/github.com/gorilla/websocket/conn.go:513 +0x53
github.com/googollee/go-engine.io/transport/websocket.wrapper.NextWriter(0xc000608420, 0x0, 0xc00057fcc0, 0xaf359c, 0xc0002012a8, 0xc00057fca8)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-engine.io/transport/websocket/wrapper.go:47 +0x42
github.com/googollee/go-engine.io/packet.(*encoder).NextWriter(0xc0000ffca0, 0x7fb25c071000, 0x4, 0x1, 0x0, 0x0, 0x0)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-engine.io/packet/encoder.go:20 +0x40
github.com/googollee/go-engine%2eio.(*session).nextWriter(0xc0003e84d0, 0x0, 0x4, 0x0, 0x1, 0x0, 0x1)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-engine.io/session.go:155 +0x69
github.com/googollee/go-engine%2eio.(*session).NextWriter(0xc0003e84d0, 0x0, 0xc000201290, 0x0, 0xc000773068, 0xc00057fef4)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-engine.io/session.go:103 +0x3d
github.com/googollee/go-socket.io/parser.(*Encoder).Encode(0xc0000ffcb0, 0x3, 0x0, 0x0, 0x7e, 0x1, 0xc0005693b0, 0x1, 0x1, 0x0, ...)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-socket.io/parser/encoder.go:29 +0x4d
github.com/googollee/go-socket%2eio.(*conn).serveWrite(0xc0001c4380)
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-socket.io/conn.go:183 +0x1be
created by github.com/googollee/go-socket%2eio.(*conn).connect
	/data/landun/workspace/go_application/vendor/github.com/googollee/go-socket.io/conn.go:113 +0x22a
```

**Comment by cheaterlin** [comment]
@erkie @mrfoe7 need your help

**Comment by mrfoe7** [comment]
@cheaterlin Hi
Please, tell me about your client. Is it connected to target web-server?

**Comment by cheaterlin** [comment]
I think it's not the problem of socket.io client v2.0.
I have simply read the go-socket.io code. It use a chan to queue the write request, concurrent write should not occurs except the following case.
The second panic info show me:
go-engine.io@v1.4.2 session.go line 69
```
func (s *session) NextReader() (FrameType, io.ReadCloser, error) {
	for {
		ft, pt, r, err := s.nextReader()
		if err != nil {
			return 0, nil, err
		}
		switch pt {
		case base.PING:
			err := func() error {
				w, err := s.nextWriter(ft, base.PONG)
				if err != nil {
					return err
				}
				io.Copy(w, r)
				return w.Close()
			}()
			r.Close()
			if err != nil {
				s.Close()
				return 0, nil, err
			}
			s.setDeadline()
		case base.CLOSE:
			r.Close()
			s.Close()
			return 0, nil, io.EOF
		case base.MESSAGE:
			return FrameType(ft), r, nil
		}
		r.Close()
	}
}
```
the
```
w, err := s.nextWriter(ft, base.PONG)
if err != nil {
	return err
}
io.Copy(w, r)
return w.Close()
```
may make a concurrent write as it's in the
go-socket.io@master conn.go line 114 `go c.serveRead()`.
In `go c.serveWrite()` you may write it too!

**Comment by cheaterlin** [comment]
> @cheaterlin Hi
> Please, tell me about your client. Is it connected to target web-server?

Yes, the client is a common web js client, it's connected to my server waiting me to push him message. As the client may be behind the NAT, it need to connect me and tell me who he is(by login), keeping the connection, i may push him the message any time he has a message.

**Comment by cheaterlin** [comment]
I've read the go-socket.io code for several hours. I find out that, you use a chan to queue the custom write request, it's ok. And you use a 'util.go'(go-engine.io) writeCloser with lock to protect the write operation for PONG message, it seems ok, and it should been ok. The only exception is that go-engine.io@v1.4.2 conn.go line 221, 'w, err := conn.NextWriter(ft, base.PONG)', the closer is not protected.

**Comment by cheaterlin** [comment]
> I've read the go-socket.io code for several hours. I find out that, you use a chan to queue the custom write request, it's ok. And you use a 'util.go'(go-engine.io) writeCloser with lock to protect the write operation for PONG message, it seems ok, and it should been ok. The only exception is that go-engine.io@v1.4.2 conn.go line 221, 'w, err := conn.NextWriter(ft, base.PONG)', the closer is not protected.

engine.io@master(diff with v1.4.1) seems have solved this problem several times. Finally, it use wrapper(go-engin.io/transport/websocket/wrapper.go line 21 'func newWrapper(conn *websocket.Conn) wrapper')to solve this problem robustly. I will fork this repo to use master version of engine.io(Commits on Sep 24, 2019). Maybe it will no longer panic :)

**Comment by zhongzhong0505** [comment]
cool

**Comment by mrfoe7** [comment]
@cheaterlin Thanks for your work. I will happy if you suggest PR to go-egine

**Comment by googollee** [comment]
v2 doesn't exist now so it should be no bugs of v2 yet.

I think the more general issue is, how to prevent concurrent reading/writing. I try to prevent it by testing on v1, but it can't capture all cases. I also try to use locking to prevent it on v0.9, which harm the performance and also have deadlock issues.
