### ISSUE TITLE
Does go-socket.io support  Thread Safety?  fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by sunlianqiang** [googollee/go-socket.io#393]
**Describe the bug**
I supposed go-socket.io should support Thread Safety， so I wrote code like this 

```golang
func BroadcastNotice(n Notice) {
	server.BroadcastToRoom("ceres", "notice", n)
}
```
and reuse this function in many modules. But when gorutines increase, the program panic. The log like below:

```golang
2020/09/24 10:57:34.120 [D] [asm_amd64.s:1357]  ------------ queue dump start:2020-09-24 10:57:34.120136708 +0000 UTC m=+804
fatal error: concurrent map iteration and map write
0.027910578------------

goroutine 34150 [running]:
2020/09/24 10:57:34.120 [D] [map.go:333]  Queue for pkg edge_aut:
runtime.throw(0x10e5149, 0x26)
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:774 +0x72 fp=0xc003cfb570 sp=0xc003cfb540 pc=0x42f5e2
runtime.mapiternext(0xc003cfb698)
2020/09/24 10:57:34.120 [D] [asm_amd64.s:1357]  ------------ queue dump end------------
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/map.go:858 +0x579 fp=0xc003cfb5f8 sp=0xc003cfb570 pc=0x40f589
2020/09/24 10:57:35.550 [D] [asm_amd64.s:1357]  RefreshPkgMap, Tick at 2020-09-24 10:57:35.5499572 +0000 UTC m=+8041.4577310
41
2020/09/24 10:57:35.575 [D] [pkgMap.go:156]  get pkg success, list len:109
2020/09/24 10:57:35.575 [D] [pkgMap.go:177]  RefreshPkgMap success
2020/09/24 10:57:49.868 [I] [mongoServerVersion.go:26]  RefreshPackageVersion, start
runtime.mapiterinit(0x1048ea0, 0xc002899140, 0xc003cfb698)
2020/09/24 10:57:49.868 [D] [mongoServerVersion.go:82]  GetOperationLog start

	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/map.go:848 +0x1c3 fp=0xc003cfb618 sp=0xc003cfb5f8 pc=0x40ef23
net/http.Header.Clone(0xc002899140, 0xc003ad4400)
	/usr/local/Cellar/go/1.13.6/libexec/src/net/http/header.go:89 +0x84 fp=0xc003cfb708 sp=0xc003cfb618 pc=0x703994
net/http.(*response).WriteHeader(0xc001d715e0, 0xc8)
	/usr/local/Cellar/go/1.13.6/libexec/src/net/http/server.go:1130 +0x23e fp=0xc003cfb880 sp=0xc003cfb708 pc=0x710c2e
net/http.(*response).write(0xc001d715e0, 0x5, 0xc005e4c640, 0x5, 0x40, 0x0, 0x0, 0xc003cfb9f8, 0xb4da7f, 0xc000d8ca08)
	/usr/local/Cellar/go/1.13.6/libexec/src/net/http/server.go:1558 +0x406 fp=0xc003cfb980 sp=0xc003cfb880 pc=0x713236
net/http.(*response).Write(0xc001d715e0, 0xc005e4c640, 0x5, 0x40, 0xb4a0d0, 0xc000d8ca08, 0xc000d8ca34)
	/usr/local/Cellar/go/1.13.6/libexec/src/net/http/server.go:1541 +0x56 fp=0xc003cfb9e0 sp=0xc003cfb980 pc=0x712d56
github.com/astaxie/beego/context.(*Response).Write(0xc000f15f20, 0xc005e4c640, 0x5, 0x40, 0xb4e56a, 0xc000d8c9e0, 0x0)
	/Users/slq/Codes/Golang/pkg/mod/github.com/astaxie/beego@v1.12.2/context/context.go:218 +0x55 fp=0xc003cfba28 sp=0xc003cfb9e0 pc=0x8281c5
bytes.(*Buffer).WriteTo(0xc000d8ca08, 0x1255d60, 0xc000f15f20, 0xc003cfbac0, 0x441777, 0xc0024ce1a8)
	/usr/local/Cellar/go/1.13.6/libexec/src/bytes/buffer.go:239 +0xb5 fp=0xc003cfba78 sp=0xc003cfba28 pc=0x50b0a5
github.com/googollee/go-engine.io/payload.(*encoder).Close(0xc000d8c9e0, 0xc0024ce1ac, 0xc003cfbb00)
	/Users/slq/Codes/Golang/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/payload/encoder.go:80 +0x17b fp=0xc003cfbaf8 sp=0xc003cfba78 pc=0xb49e3b
github.com/googollee/go-engine%2eio.(*writer).Close.func1()
	/Users/slq/Codes/Golang/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/util.go:26 +0x8a fp=0xc003cfbb68 sp=0xc003cfbaf8 pc=0xb69e2a
sync.(*Once).doSlow(0xc002899278, 0xc003cfbc18)
	/usr/local/Cellar/go/1.13.6/libexec/src/sync/once.go:66 +0xe3 fp=0xc003cfbc08 sp=0xc003cfbb68 pc=0x47a373
sync.(*Once).Do(...)
	/usr/local/Cellar/go/1.13.6/libexec/src/sync/once.go:57
github.com/googollee/go-engine%2eio.(*writer).Close(0xc002899260, 0x0, 0x0)
	/Users/slq/Codes/Golang/pkg/mod/github.com/googollee/go-engine.io@v1.4.1/util.go:23 +0x7d fp=0xc003cfbc40 sp=0xc003cfbc08 pc=0xb6964d
github.com/googollee/go-socket.io/parser.(*Encoder).writePacket(0xc0048c3e80, 0x12617e0, 0xc002899260, 0x0, 0xc003957010, 0xa, 0x0, 0x0, 0x1acf1c8, 0x0, ...)
	/Users/slq/Codes/Golang/pkg/mod/github.com/googollee/go-socket.io@v1.4.2/parser/encoder.go:119 +0x367 fp=0xc003cfbd90 sp=0xc003cfbc40 pc=0xb6cf07
github.com/googollee/go-socket.io/parser.(*Encoder).Encode(0xc0048c3e80, 0x0, 0xc003957010, 0xa, 0x0, 0x0, 0x1acf1c8, 0x0, 0x0, 0x0, ...)
	/Users/slq/Codes/Golang/pkg/mod/github.com/googollee/go-socket.io@v1.4.2/parser/encoder.go:35 +0xd3 fp=0xc003cfbe50 sp=0xc003cfbd90 pc=0xb6c9d3
github.com/googollee/go-socket%2eio.(*conn).serveWrite(0xc00014e150)
	/Users/slq/Codes/Golang/pkg/mod/github.com/googollee/go-socket.io@v1.4.2/conn.go:176 +0x1da fp=0xc003cfbfd8 sp=0xc003cfbe50 pc=0xb705fa
runtime.goexit()
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc003cfbfe0 sp=0xc003cfbfd8 pc=0x45d321
created by github.com/googollee/go-socket%2eio.(*conn).connect
	/Users/slq/Codes/Golang/pkg/mod/github.com/googollee/go-socket.io@v1.4.2/conn.go:106 +0x229

goroutine 1 [chan receive, 134 minutes]:
github.com/astaxie/beego.(*App).Run(0xc000153020, 0x0, 0x0, 0x0)
	/Users/slq/Codes/Golang/pkg/mod/github.com/astaxie/beego@v1.12.2/app.go:238 +0x253
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/Users/slq/Codes/Golang/pkg/mod/github.com/astaxie/beego@v1.12.2/beego.go:72 +0x62
main.main()
	/Users/slq/Codes/Golang/src/github.com/AgoraLab/sre_ceres/platform_web/main.go:166 +0x3ac
...
```

I think maybe it's because go-socket.io doesn't support thread safety, so I add a sync.Mutex like below
```golang
func BroadcastNotice(n Notice) {
	// add mutex to avoid bug:concurrent map iteration and map write
	socketMutex.Lock()
	defer socketMutex.Unlock()

	server.BroadcastToRoom("ceres", "notice", n)
}
```

My problem is:
1. Does go-socket.io support  Thread Safety?
2. What's the best way to use go-socket.io in threads environment?

**To Reproduce**
Brief code to reproduce the behavior.

use server.BroadcastToRoom() in gorutines

**Expected behavior**

No panic

**Environment (please complete the following information):**
 - Go version: 1.13.6
 - Server version: go-socket.io v1.4.2
 - Client version: socket.io-client": "^1.4.0"

**Additional context**

**Comment by erkie** [comment]
It should! This is a bug unfortunately. We'd love any help or PR's to fix it.

**Comment by evsamsonov** [comment]
Which branch is the base for v1.4.4? I tried to use v1.4 but there aren't some methods (for example, BroadcastToRoom). master has BroadcastToRoom but NewServer returns 1 variables unlike v1.4.4

**Comment by erkie** [comment]
@evsamsonov 1.4 is master branch I do believe?

**Comment by mrfoe7** [comment]
@sunlianqiang @evsamsonov Is it actually? 

it looks like this is not relevant

**Comment by evsamsonov** [comment]
@mrfoe7 yes, this is not relevant
