### ISSUE TITLE
Interface conversion panic in redisBroadcast.getNumSub

### ISSUE THREAD

**Issue by zhangkai803** [googollee/go-socket.io#521]
**Describe the bug**

I'm trying to get the count of room members by `server.RoomLen(s.Namespace(), "myRoomId")` based on [Base example with using std net/http](https://github.com/googollee/go-socket.io/tree/master/_examples#base-example-with-using-std-nethttp).
It works just fine when i make testing connection one by one. When i make more connections and quicker, it gives me a `go panic` like below:

```log
panic: interface conversion: interface {} is []uint8, not []interface {}

goroutine 353 [running]:
github.com/googollee/go-socket%2eio.(*redisBroadcast).getNumSub(0xc000122090, 0xc0000162e0, 0x12, 0x0, 0x0, 0x0)
...
```

**To Reproduce**
Brief code to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**

 - Go version: v1.15.3
 - Server version: go-socket.io v1.6.1
 - Client version: socket.io v2.4.0

**Additional context**

code:
![image](https://user-images.githubusercontent.com/41277964/144013971-c3aa9942-24ce-46c9-b31d-c4ea666df4b4.png)

output:
![image](https://user-images.githubusercontent.com/41277964/144013495-2e530d69-7fc4-40f6-accb-894d93bd405f.png)

Full panic info:

```log
panic: interface conversion: interface {} is []uint8, not []interface {}

goroutine 353 [running]:
github.com/googollee/go-socket%2eio.(*redisBroadcast).getNumSub(0xc000122090, 0xc0000162e0, 0x12, 0x0, 0x0, 0x0)
	/Users/k/go/pkg/mod/github.com/googollee/go-socket.io@v1.6.1/redis_broadcast.go:339 +0x3bf
github.com/googollee/go-socket%2eio.(*redisBroadcast).Len(0xc000122090, 0x14f45c3, 0x4, 0x0)
	/Users/k/go/pkg/mod/github.com/googollee/go-socket.io@v1.6.1/redis_broadcast.go:257 +0x2a5
github.com/googollee/go-socket%2eio.(*Server).RoomLen(0xc00000e400, 0x14f40fc, 0x1, 0x14f45c3, 0x4, 0x0)
	/Users/k/go/pkg/mod/github.com/googollee/go-socket.io@v1.6.1/server.go:175 +0x86
main.main.func1(0x1539000, 0xc00041c0c0, 0x0, 0x0)
	/Users/k/go_projects/ws_demo/main.go:32 +0x4f8
github.com/googollee/go-socket%2eio.(*namespaceHandler).dispatch(0xc000072370, 0x1539000, 0xc00041c0c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/k/go/pkg/mod/github.com/googollee/go-socket.io@v1.6.1/namespace_handler.go:71 +0x90
github.com/googollee/go-socket%2eio.(*conn).connect(0xc00041c060, 0x0, 0x0)
	/Users/k/go/pkg/mod/github.com/googollee/go-socket.io@v1.6.1/connection.go:115 +0x468
github.com/googollee/go-socket%2eio.newConn(0x1538aa0, 0xc0000a4000, 0xc00000e380, 0x0, 0x0)
	/Users/k/go/pkg/mod/github.com/googollee/go-socket.io@v1.6.1/connection.go:57 +0x307
github.com/googollee/go-socket%2eio.(*Server).serveConn(0xc00000e400, 0x1538aa0, 0xc0000a4000)
	/Users/k/go/pkg/mod/github.com/googollee/go-socket.io@v1.6.1/server.go:208 +0x51
created by github.com/googollee/go-socket%2eio.(*Server).Serve
	/Users/k/go/pkg/mod/github.com/googollee/go-socket.io@v1.6.1/server.go:101 **+0x112**
```

Hoping for a solution.
Thanks for reply.

**Comment by zhangkai803** [comment]
Am I using it in the wrong way?
